# 隐私政策 (Privacy Policy)

**最后更新日期 (Last Updated):** 2026-01-30

## 1. 信息收集 (Information Collection)
本应用（糖葫芦 / Tanghulu）高度尊重并保护用户的个人隐私信息。
- **不收集个人信息**: 我们承诺不通过本应用收集、存储或上传您的任何个人身份信息。
- **无服务器关联**: 开发者未架设任何服务器用于收集用户数据或跟踪用户行为。
- **本地存储**: 应用产生的所有数据仅保留在您的设备本地，为了更好的用户体验而存在。

The app (Tanghulu) respects and protects the privacy of all users.
- **No Personal Information Collected**: We do not collect, store, or upload any Personally Identifiable Information (PII) through this app.
- **No Server Association**: The developer does not operate servers to collect user data or track user behavior.
- **Local Storage Only**: All data generated by the app is stored locally on your device solely to improve user experience.

## 2. 第三方服务 (Third-Party Services)
- **无广告**: 本应用不包含任何第三方广告 SDK。
- **无追踪**: 本应用不包含任何用于数据采集或崩溃分析的第三方 SDK。

- **No Ads**: This app does not contain any third-party advertising SDKs.
- **No Tracking**: This app does not contain any third-party SDKs for data collection or crash analysis.

## 3. 政策变更 (Changes to This Privacy Policy)
我们可能会不定期更新我们的隐私政策。任何更改都将在此页面上发布。建议您定期查看本页面以获取最新信息。

We may update our Privacy Policy from time to time. Any changes will be posted on this page. You are advised to review this page periodically for any changes.

## 4. 联系我们 (Contact Us)
如果您对我们的隐私政策有任何疑问或建议，请随时联系我们。
If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us.

**Email**: husanbo@gmail.com
